remote_theme: daattali/beautiful-jekyll@5.0.0
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from

title: A tree, forest and cloud blog
author: Christian Baumgartner

navbar-links:
  Blog: "/"
  About Me / Contact: "aboutme"
  Git Hub Pages: "githubpages"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"

avatar: "/assets/img/me2.jpg"
round-avatar: true

# If you want to have an image logo in the top-left corner instead of having the title of the website,
# then specify the following parameter
#title-img: /path/to/image


# --- Footer social media links --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
social-network-links:
  email: "contact@treeforest.cloud"
  github: backbone2k
  twitter: backbone2k
  linkedin: christianbaumgartner
  
share-links-active:
  twitter: true
  linkedin: true

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "MyWebsite.com"

excerpt_length: 50
feed_show_excerpt: false
feed_show_tags: false

keywords: "microsoft,identity,authentication"


link-col: "#404040"
mobile-theme-col: "#0085A1"

site-css:
  - "/assets/css/custom-styles.css"

#site-js:
#  - "/assets/js/custom-script.js"

utterances:
  repository: backbone2k/backbone2k.github.io
  issue-term: pathname
  theme: github-light
  label: blog-comments

date_format: "%B %-d, %Y"

timezone: "Europe/Berlin"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
#permalink: /:year-:month-:day-:title/
paginate: 10
paginate_path: "/page:num/"

kramdown:
  input: GFM


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      social-share: true
  -
    scope:
      path: "notblog"
    values:
      layout: "post"
      comments: true
      social-share: true      
  -
    scope:
      path: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"


exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

